services:
  auction-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auction-service
    ports:
      - "5001:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - microservices-net
networks:
  microservices-net:
    external: true