services:
  user-auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: user-auth-service
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - microservices-net
networks:
  microservices-net:
    external: true