version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: auction-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - microservices-net  
volumes:
  mongo_data:
networks:
  microservices-net:
    external: true
