services:
  front:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: front
    ports:
      - "3000:3000"
    networks:
      - microservices-net
networks:
  microservices-net:
    external: true
